---
title: "3700 Project"
author: "Kelly Money"
date: "4/16/2020"
output: flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    vertical_layout: fill
    theme: solar
---

.chart-title {  /* chart_title  */
   font-size: 30px;
   font-family: Algerian;


```{r}


```


```{r setup, include=FALSE}
#load packages
library(flexdashboard)
library(coronavirus) 
library(tidyr)
library(DT)
library(dplyr)
library(knitr)
library(plotly)
library(testthat)
library(devtools)
library(remotes)
library(leaflet)
library(leafpop)
library(purrr)
library(shinythemes)
library(xaringan)
library(gganimate)



```

```{r, include=FALSE}
#load 'coronavirus' package 
devtools::install_github("covid19r/coronavirus", force = TRUE)





```


```{r, include=FALSE}
#In order to present the most updated version of the data, check the original data for updates
coronavirus::update_datasets(silence=TRUE)
data("coronavirus")

#cool little trick to load function from a package that you don't want to load
`%>%` <- magrittr::`%>%`



```



```{r pressure, echo=FALSE}

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
